name: CI - Docker PHP Test

on:
  push:
    branches: [ main ]

jobs:
  php-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t php-app .

      - name: Run PHPUnit tests
        run: docker run --rm php-app vendor/bin/phpunit tests

